services:
  symfony:
    image: bitnami/symfony
    container_name: symfony_app
    ports:
      - "80:8000"
    environment:
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
      - DATABASE_HOST=mysql
      - SYMFONY_DATABASE_PASSWORD=symfony
    volumes:
      - ./web_app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"    #this line maps your pc port to the container port
    depends_on:
      - mysql    #this line links this container to the db container
    environment:
      PMA_HOST: mysql